// Top-level build file where you can add configuration options common to all sub-projects/modules.
// This file tells Gradle WHERE to find plugins/dependencies and WHICH plugins to use.

plugins {
    // Android Application Plugin — lets Gradle build .APK files
    id 'com.android.application' version '8.3.2' apply false
}
